#!/system/bin/sh
#################################
##   CronMod A2SD++ -- Final   ##
## Written by CronicCorey @xda ##
##           40a2sd            ##
#################################

## Set SD cache size
if [ -e /sys/devices/virtual/bdi/179:0/read_ahead_kb ]
then
  /system/xbin/echo "2048" > /sys/devices/virtual/bdi/179:0/read_ahead_kb;
fi;

## Unmount /sd-ext if it already mounted
busybox umount /sd-ext;

## Mount mmcblk0p2 to /sd-ext
busybox mount -o noatime,nodiratime,nosuid,nodev  /dev/block/mmcblk0p2 /sd-ext;
mountext=`busybox mount | egrep 'ext2|ext3|ext4'`;
if [ -n "$mountext" ]; 
then
busybox chown 1000:1000 /sd-ext;
busybox chmod 771 /sd-ext;
fi;

## Create A2SD directories
if [ ! -e /sd-ext/app ]
then
busybox mkdir /sd-ext/app;
busybox mv /data/app/* /sd-ext/app;
fi;

if [ ! -e /sd-ext/dalvik-cache ]
then
busybox mkdir /sd-ext/dalvik-cache;
busybox mv /data/dalvik-cache/* /sd-ext/dalvik-cache;
fi;

## Bind A2SD directories
busybox mount -o bind /sd-ext/app /data/app;
busybox chown 1000:1000 /sd-ext/app;
busybox chmod 771 /sd-ext/app;

busybox mount -o bind /sd-ext/dalvik-cache /data/dalvik-cache;
busybox chown 1000:1000 /sd-ext/dalvik-cache;
busybox chmod 771 /sd-ext/dalvik-cache;

sync;

